use_frameworks!

platform :ios, '10.0'

target 'TestCocoapodsConfigurationsRepo_Example' do
  pod 'TestCocoapodsConfigurationsRepo', :path => '../'

  target 'TestCocoapodsConfigurationsRepo_Tests' do
    inherit! :search_paths

    
  end
end
